# Generated by Django 5.0.7 on 2024-07-18 21:57

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def create_periodic_task(apps, schema_editor):
    crontab_schedule, created = CrontabSchedule.objects.get_or_create(
        minute='*/10',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    PeriodicTask.objects.update_or_create(
        name='fetch_and_save_clients',
        defaults={
            'task': 'clients.tasks.fetch_and_save_clients',
            'crontab': crontab_schedule,
            'enabled': True,
        }
    )


def delete_periodic_task(apps, schema_editor):
    PeriodicTask.objects.filter(name='fetch_and_save_clients').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.RunPython(create_periodic_task, reverse_code=delete_periodic_task),
    ]
